### ISSUE TITLE
部署失败了，帮我看看，哪里有问题呢？

### ISSUE THREAD

**Issue by abellq** [gwang74/moac_xpress#4]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@6.10.3
3 info using node@v8.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle moacxpress@0.0.0~prestart: moacxpress@0.0.0
6 info lifecycle moacxpress@0.0.0~start: moacxpress@0.0.0
7 verbose lifecycle moacxpress@0.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle moacxpress@0.0.0~start: PATH: C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\moac_xpress-master\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\apache-ant-1.9.4\bin;C:\android-ndk-r10c;C:\adt-bundle-windows-x86-20131030\sdk\platform-tools;C:\nodejs\;C:\jdk1.8.0_161\bin;C:\jdk1.8.0_161\jre\bin;C:\android-sdk\platform-tools;C:\android-sdk\tools;C:\openssh;C:\Program Files\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Users\Administrator\AppData\Roaming\npm;C:\Program Files\Microsoft VS Code\bin
9 verbose lifecycle moacxpress@0.0.0~start: CWD: C:\moac_xpress-master
10 silly lifecycle moacxpress@0.0.0~start: Args: [ '/d /s /c', 'node ./bin/www' ]
11 silly lifecycle moacxpress@0.0.0~start: Returned: code: 1  signal: null
12 info lifecycle moacxpress@0.0.0~start: Failed to exec start script
13 verbose stack Error: moacxpress@0.0.0 start: `node ./bin/www`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:326:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid moacxpress@0.0.0
15 verbose cwd C:\moac_xpress-master
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
18 verbose node v8.10.0
19 verbose npm  v6.10.3
20 error code ELIFECYCLE
21 error errno 1
22 error moacxpress@0.0.0 start: `node ./bin/www`
22 error Exit status 1
23 error Failed at the moacxpress@0.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by abellq** [comment]
补充“命令行”下的信息：
================================================
C:\moac_xpress-master>npm run start

> moacxpress@0.0.0 start C:\moac_xpress-master
> node ./bin/www

{"message":"connected to moac vnode at http://localhost:8545","level":"info"}
GET /index.html 304 8.819 ms - -
GET /static/css/app.301c315b3764404ea01cc113e860f12c.css 304 1.891 ms - -
GET /static/js/manifest.3ad1d5771e9b13dbdad2.js 304 3.049 ms - -
GET /static/js/vendor.4ef4e1547c7cab5ecc6c.js 304 22.201 ms - -
GET /static/js/app.e679147e8d25564c479a.js 304 30.083 ms - -
GET /scss/getInitConfig 200 10.388 ms - 499
GET /scss/getContract 304 1.765 ms - -
POST /scss/initConfig 200 20.329 ms - 35
{"message":"baseaddr has enough balance!","level":"info"}
{ AssertionError [ERR_ASSERTION]: Invalid callback specified.
    at wrapCallback (C:\moac_xpress-master\node_modules\solc\wrapper.js:16:5)
    at runWithReadCallback (C:\moac_xpress-master\node_modules\solc\wrapper.js:4
2:26)
    at compileStandard (C:\moac_xpress-master\node_modules\solc\wrapper.js:83:14
)
    at Object.compileStandardWrapper (C:\moac_xpress-master\node_modules\solc\wr
apper.js:90:14)
    at deployvnodepool (C:\moac_xpress-master\public\javascripts\scs.js:293:19)
    at deploy (C:\moac_xpress-master\public\javascripts\scs.js:93:17)
    at Layer.handle [as handle_request] (C:\moac_xpress-master\node_modules\expr
ess\lib\router\layer.js:95:5)
    at next (C:\moac_xpress-master\node_modules\express\lib\router\route.js:137:
13)
    at Route.dispatch (C:\moac_xpress-master\node_modules\express\lib\router\rou
te.js:112:3)
    at Layer.handle [as handle_request] (C:\moac_xpress-master\node_modules\expr
ess\lib\router\layer.js:95:5)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }
{ AssertionError [ERR_ASSERTION]: Invalid callback specified.
    at wrapCallback (C:\moac_xpress-master\node_modules\solc\wrapper.js:16:5)
    at runWithReadCallback (C:\moac_xpress-master\node_modules\solc\wrapper.js:4
2:26)
    at compileStandard (C:\moac_xpress-master\node_modules\solc\wrapper.js:83:14
)
    at Object.compileStandardWrapper (C:\moac_xpress-master\node_modules\solc\wr
apper.js:90:14)
    at deployvnodepool (C:\moac_xpress-master\public\javascripts\scs.js:293:19)
    at deploy (C:\moac_xpress-master\public\javascripts\scs.js:93:17)
    at Layer.handle [as handle_request] (C:\moac_xpress-master\node_modules\expr
ess\lib\router\layer.js:95:5)
    at next (C:\moac_xpress-master\node_modules\express\lib\router\route.js:137:
13)
    at Route.dispatch (C:\moac_xpress-master\node_modules\express\lib\router\rou
te.js:112:3)
    at Layer.handle [as handle_request] (C:\moac_xpress-master\node_modules\expr
ess\lib\router\layer.js:95:5)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }
{"error":"abort({\"generatedMessage\":false,\"name\":\"AssertionError [ERR_ASSER
TION]\",\"code\":\"ERR_ASSERTION\",\"actual\":false,\"expected\":true,\"operator
\":\"==\"}). Build with -s ASSERTIONS=1 for more info.","level":"error","message
":"uncaughtException: abort({\"generatedMessage\":false,\"name\":\"AssertionErro
r [ERR_ASSERTION]\",\"code\":\"ERR_ASSERTION\",\"actual\":false,\"expected\":tru
e,\"operator\":\"==\"}). Build with -s ASSERTIONS=1 for more info.\n  No stack t
race","exception":true,"date":"Thu Aug 15 2019 20:47:23 GMT+0800 (中国标准时间)"
,"process":{"pid":3632,"uid":null,"gid":null,"cwd":"C:\\moac_xpress-master","exe
cPath":"C:\\nodejs\\node.exe","version":"v8.10.0","argv":["C:\\nodejs\\node.exe"
,"C:\\moac_xpress-master\\bin\\www"],"memoryUsage":{"rss":51412992,"heapTotal":3
3226752,"heapUsed":30769416,"external":16800596}},"os":{"loadavg":[0,0,0],"uptim
e":13268.1272419},"trace":[]}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! moacxpress@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the moacxpress@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-08-15T1
2_47_27_026Z-debug.log

C:\moac_xpress-master>

**Comment by gwang74** [comment]
智能合约编译时出错了，估计solc版本问题。可能需要你在工程目录下执行
```nodejs
npm uninstall solc
```
卸载后再执行
```nodejs
npm install solc@0.4.24
```
安装后再尝试是否可以正常发链。
另外，可以提供下你的操作环境吗？我们在windows10测试没有出现该问题，所以想记录下。

**Comment by abellq** [comment]
嗯，更换了solc版本，已经可以正常发链了。谢谢！
附：
windows 7  32位
