### ISSUE TITLE
scs节点连接vnode的SCSservice服务失败

### ISSUE THREAD

**Issue by jyj545** [gwang74/moac_xpress#6]
vnode配置:{
 "ip":"127.0.0.1",
  "ShowToPublic": true,
  "VnodeServiceCfg": ":50062",
  "SCSservice": true,
  "VnodeBeneficialAddress" : "0x5b4e516df9c2f148fe0dedb78df8d926aef78da1"
}
userconfig配置:{
    "VnodeServiceCfg": "127.0.0.1:50062",
    "DataDir": "./scsdata",
    "LogPath": "./_logs",
    "Beneficiary": "0x5b4e516df9c2f148fe0dedb78df8d926aef78da1",
    "VnodechainId": 101,
    "Capability": 10,
    "ReconnectInterval": 5,
    "LogLevel": 4,
    "BondLimit":2,
    "ReWardMin":0.0001
}
错误: 8:try to reconnect vnode... 
DEBUG[08-16|15:42:56.250] 8:GetCurrentVnodeString: 127.0.0.1:50062, CurrentVnodeIndex: 0, vnodeListLen: 1 
DEBUG[08-16|15:42:56.250] 8:try to connect vnode: 127.0.0.1:50062 
DEBUG[08-16|15:42:56.251] 8:pushmsg.go->runScsRegisterMsg 
DEBUG[08-16|15:42:56.251] 1707:runScsRegisterMsg started go-routine to send the handshake message to Vnode... 
DEBUG[08-16|15:42:56.251] 1706:runScsRegisterMsg started the stream.Recv loop ... 
DEBUG[08-16|15:42:56.251] 1707:ScsRegister stream Send [requestid:"0xbC52d159a2080Db8Ee7d0E8C2541A7ac6Be438DE-184" timestamp:"\000\000\000\000]V^\200" requestflag:true type:"\000\000\000\004" status:"\377\377\377\377" scsid:"0xbC52d159a2080Db8Ee7d0E8C2541A7ac6Be438DE" msghash:"\371\001\314\205shake\271\001\301-----BEGIN publickey-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA+MqrymgNA3KSD0MYWMBT\nsQQ4D23ffxAfmgSgJo6ZMCOqNQaBxYmvuQlx1vJ4M3rIdXxBaub4FK4IveAoJsdw\nBD2pFdQqSwSh6+qq9vE8SOO6IiHf+XhcS3vVrYHKi6AyNiEvM2rd0gAi4obl4nhN\neAo1gOizBlIN00C0io+XwBqogG+z7smn/IddpPbDOBE4mk3oZkHksZOX9opCLn8I\nxle0Tox3XsdgFmOjVMzqE6lRiUjPdH2VPf5OXExAu89JhmHPkX5dJufm/pLo9NkJ\nnorFUzFnAwKy8556mjrqkeE+GCABkbpT6gxROuy1N8b5FcrFml3vpK1MzGXnAHg5\ncwIDAQAB\n-----END publickey-----\n\ne" ] 
DEBUG[08-16|15:42:56.252] 1706:runScsRegisterMsg exit the stream.Recv loop as the stream got EOF... 
ERROR[08-16|15:42:56.252] 8:Cannot connect vnode! EOF

**Comment by gwang74** [comment]
配置没有问题，那应该是vnode节点的问题，没有正常启动或者同步失败。请确认下vnode是否正常
```
./moac attach "http://127.0.0.1:8545"
```
连接下控制看能否成功

**Comment by jyj545** [comment]
./moac-linux-amd64 attach "http://127.0.0.1:8545"
Start MOAC nuwa 1.0.10-rc ...
Start new console with input config
2019/08/20 09:38:11 listen tcp 127.0.0.1:6060: bind: address already in use
INFO [08-20|09:38:11.965] 1:[rpc/http.go->Client.sendHTTP] 
Init finished!......
Welcome to the MOAC JavaScript console!

INFO [08-20|09:38:11.972] 15:[rpc/http.go->Client.sendHTTP] 
instance: Moac/v1.0.10-rc-caeb2b5e/linux-amd64/go1.11
INFO [08-20|09:38:11.974] 15:[rpc/http.go->Client.sendHTTP] 
INFO [08-20|09:38:11.976] 1:[rpc/http.go->Client.sendHTTP] 
 modules: admin:1.0 chain3:1.0 mc:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0

>

**Comment by jyj545** [comment]
ｌｉｎｕｘ下vnode创建的keystore存在哪里在

**Comment by jyj545** [comment]
2019-08-20 22:24:49 - info: microChain created at address: 0xadc8c0903d2333e3497176e6e273e801c48d4006
2019-08-20 22:24:49 - info: Add funding to microChain!
2019-08-20 22:24:49 - info: addFund 0xadc8c0903d2333e3497176e6e273e801c48d4006
Error: invalid JSON argument 0: hex string has length 0, want 40 for common.Address
    at Object.InvalidResponse (/home/jyj/work/moac_xpress/node_modules/chain3/lib/chain3/errors.js:44:16)
    at RequestManager.send (/home/jyj/work/moac_xpress/node_modules/chain3/lib/chain3/requestmanager.js:56:22)
    at Mc.send [as getTransactionCount] (/home/jyj/work/moac_xpress/node_modules/chain3/lib/chain3/method.js:148:58)
    at getNonce (/home/jyj/work/moac_xpress/public/javascripts/utils.js:59:27)
    at sendtx (/home/jyj/work/moac_xpress/public/javascripts/utils.js:44:29)
    at Object.addMicroChainFund (/home/jyj/work/moac_xpress/public/javascripts/utils.js:256:5)
    at deploy (/home/jyj/work/moac_xpress/public/javascripts/scs.js:105:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: invalid JSON argument 0: hex string has length 0, want 40 for common.Address
    at Object.InvalidResponse (/home/jyj/work/moac_xpress/node_modules/chain3/lib/chain3/errors.js:44:16)
    at RequestManager.send (/home/jyj/work/moac_xpress/node_modules/chain3/lib/chain3/requestmanager.js:56:22)
    at Mc.send [as getTransactionCount] (/home/jyj/work/moac_xpress/node_modules/chain3/lib/chain3/method.js:148:58)
    at getNonce (/home/jyj/work/moac_xpress/public/javascripts/utils.js:59:27)
    at sendtx (/home/jyj/work/moac_xpress/public/javascripts/utils.js:44:29)
    at Object.addMicroChainFund (/home/jyj/work/moac_xpress/public/javascripts/utils.js:256:5)
    at deploy (/home/jyj/work/moac_xpress/public/javascripts/scs.js:105:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2019-08-20 22:24:49 - error: uncaughtException: abort({}). Build with -s ASSERTIONS=1 for more info.
